baseURL = "https://long8v.github.io/PTIR/"
languageCode = "en-us"
title = "Paper Today I Read"
theme = "PaperMod"
paginate = 9999

[params]
  author = "long8v"
  description = "Paper reviews translated from Korean to English"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  ShowToc = true
  hideSummary = true

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "tags", "contents"]

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/long8v/PTIR"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true
