baseURL = "https://long8v.github.io/PTIR/"
title = "🍎 Paper Today I Read 🦔"
theme = "PaperMod"
paginate = 9999
defaultContentLanguage = "en"

[languages.en]
  languageName = "EN"
  weight = 1

[languages.ko]
  languageName = "KR"
  weight = 2

[params]
  author = "long8v"
  description = "Simple notes from reading papers — sometimes detailed, sometimes raw. Just my honest impressions, left as-is."
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  ShowToc = true
  hideSummary = true
  comments = true

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "tags", "contents"]

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/long8v/PTIR"

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true
